<a href="<?php echo $this->_uri->generate("topic-list", ["sectionId" => $this->section->getId()]) ?>">
    <h3>DZIAL: <?php echo $this->section->getName() ?></h3>
</a>

<div id="comment_section">
    <?php foreach ($this->messages as $message) { ?>
        <div style="color: green"><?php echo $message["message"] ?></div>
    <?php } ?>
    <ol class="comments first_level">
        <?php foreach ($this->topics as $topic) { ?>
            <li>
                <div class="comment_box commentbox1">
                    <div class="comment_text">
                        <div class="comment_author">
                            <a href="<?php echo $this->_uri->generate("topic-view", ["sectionId" => $this->section->getId(), "topicId" => $topic->getId()]) ?>" style="color: #081e30"><?php echo $topic->getName(); ?></a>
                            <span class="date">Postów: <?php echo $topic->getAmountPosts(); ?></span>
                        </div>
                        <p><?php echo $topic->getDescription(); ?></p>
                        <?php if ($topic->getLastPost()) { ?>
                            <p>
                                Ostatni post: <?php echo $topic->getLastPost()->getCreatedOnAsString() ?>
                                przez: <?php echo $topic->getLastPost()->getUser()->getUsername() ?>
                            </p>
                        <?php } ?>
                            
                        <p style="margin-top: 15px">
                            <?php if ((!$topic->isClosed() && !$topic->getSection()->isClosed()) && ($this->_guard->isGranted("ROLE_EDIT_ALL_TOPICS") || ($this->_guard->isGranted("ROLE_EDIT_TOPIC")) && $topic->getUser()->getId() == $this->_user["id"])) { ?>
                                <a href="<?php echo $this->_uri->generate("topic-edit", ["sectionId" => $this->section->getId(), "topicId" => $topic->getId()]) ?>">EDYTUJ</a>
                            <?php } ?>
                                
                            <?php if ($this->_guard->isGranted("ROLE_DELETE_TOPIC")) { ?>
                                <a href="<?php echo $this->_uri->generate("topic-remove", ["sectionId" => $this->section->getId(), "topicId" => $topic->getId(), "token" => $this->_user["token"]]) ?>">USUŃ</a>
                            <?php } ?>
                        </p>
                    </div>
                    
                    <div class="cleaner"></div>
                </div>  
            </li>
        <?php } ?>
    </ol>
</div>

<div class="cleaner"></div>
