<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    
    <?php $this->includeFile('Forum/view/layout/header.phtml'); ?>
    
    <body>
        <div id="forum_wrapper">
            <div id="forum_header"> </div>

            <div id="forum_menu">
                <ul>
                    <li><a <?php echo ($this->_menu === "home")? 'class="current' : ""; ?> href="<?php echo $this->_uri->generate("main") ?>">Home</a></li>
                    <?php if ($this->_guard->isAuthenticated()) { ?>
                        <li><a href="<?php echo $this->_uri->generate("logout") ?>" class="last">Wyloguj</a></li>
                    <?php } else { ?>
                        <li><a <?php echo ($this->_menu === "login")? 'class="current' : ""; ?> href="<?php echo $this->_uri->generate("login") ?>" class="last">Zaloguj</a></li>
                    <?php } ?>
                        
                    <?php if (!$this->_guard->isAuthenticated()) { ?>
                        <li><a <?php echo ($this->_menu === "registration")? 'class="current' : ""; ?>  href="<?php echo $this->_uri->generate("user-registration") ?>" class="last">Rejestracja</a></li>
                    <?php } ?>
                        
                    <?php if ($this->_guard->isGranted("ROLE_ADD_SECTION")) { ?>
                        <li style="float: right">
                            <a <?php echo ($this->_menu === "section-add")? 'class="current' : ""; ?> href="<?php echo $this->_uri->generate("section-add") ?>">+ dzial</a> 
                        </li>
                    <?php } ?>
                        
                    <?php if ($this->_guard->isGranted("ROLE_ADD_TOPIC") && isset($this->section) && !$this->section->isClosed()) { ?>
                        <li style="float: right">
                            <a <?php echo ($this->_menu === "topic-add")? 'class="current' : ""; ?> href="<?php echo $this->_uri->generate("topic-add", ["sectionId" => $this->section->getId()]) ?>">+ temat</a> 
                        </li>
                    <?php } ?>
                        
                    <?php if ($this->_guard->isGranted("ROLE_ADD_POST") && isset($this->topic) && !$this->topic->isClosed() && !$this->topic->getSection()->isClosed()) { ?>
                        <li style="float: right">
                            <a <?php echo ($this->_menu === "post-add")? 'class="current' : ""; ?> href="<?php echo $this->_uri->generate("post-add", ["sectionId" => $this->section->getId(), "topicId" => $this->topic->getId()]) ?>">+ post</a> 
                        </li>
                    <?php } ?> 
                </ul>   	
            </div> <!-- end of forum_menu -->

            <div id="forum_main">
                <div id="forum_content">
                    <?php $this->includeFile($this->_content, $this->_contentPath); ?>
                </div>

                <div class="cleaner"></div>
            </div>
            
            <?php $this->includeFile('Forum/view/layout/footer.phtml'); ?> 
            
        </div> 
    </body>
</html>