<div id="comment_section">
    <ol class="comments first_level">        
        <?php foreach ($this->sections as $section) { ?>
            <li>
                <div class="comment_box commentbox1">
                    <div class="comment_text">
                        <div class="comment_author">
                            <a href="<?php echo $this->_uri->generate("topic-list", ["sectionId" =>  $section->getId()]) ?>" style="color: #081e30"><?php echo $section->getName(); ?></a>
                            <span class="date">Tematów: <?php echo $section->getAmountTopics(); ?></span>
                        </div>
                        <p><?php echo $section->getDescription(); ?></p>
                        <?php if ($section->getLastTopic()) { ?>
                            <p>
                                Ostatni post w: <?php echo $section->getLastTopic()->getName() ?>
                                przez: <?php echo $section->getLastPost()->getUsername() ?>
                            </p>
                        <?php } ?>
                            
                        <p style="margin-top: 15px">
                            <?php if ($this->_guard->isGranted("ROLE_EDIT_SECTION")) { ?>
                                <a href="<?php echo $this->_uri->generate("section-edit", ["sectionId"=>$section->getId()]) ?>">EDYTUJ</a>
                            <?php } ?>
                                
                            <?php if ($this->_guard->isGranted("ROLE_DELETE_SECTION")) { ?>
                                <a href="<?php echo $this->_uri->generate("section-remove", ["sectionId"=>$section->getId(), "token"=>$this->_user["token"]]) ?>">USUŃ</a>
                            <?php } ?>
                        </p>
                    </div>
                    
                    <div class="cleaner"></div>
                </div>  
            </li>
        <?php } ?>
    </ol>
</div>

<div class="cleaner"></div>
